### ISSUE TITLE
[Feature request] Add the Shield

### ISSUE THREAD

**Issue by treybrisbane** [sunnypwang/Anvil-Calculator#4]
The list of enchantable items does not include the Shield, despite the fact that it's enchantable via an Anvil. Would be great if you could add it! 🙂 

See [the Minecraft wiki](https://minecraft.gamepedia.com/Shield#Enchantments) for the list of enchantments the Shield can have.

**Comment by sunnypwang** [comment]
Thanks. Added Shield!
