### ISSUE TITLE
[Feature request] Adding the Hoe

### ISSUE THREAD

**Issue by gretchasketch** [sunnypwang/Anvil-Calculator#5]
Of all the items to be worried about... But, I noticed the list of enchantable items does not include the Hoe and I'm _**not**_ sorry that I would like to have that added. 

The [Minecraft Wiki Hoe page](https://minecraft.gamepedia.com/Hoe#Enchantments) lists all the enchantments available, too.  Please & thanks! 🙂

**Comment by sunnypwang** [comment]
Thanks. Added Hoe!
